/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projektzespolowy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class OknGlowne extends javax.swing.JFrame {

    /**
     * Creates new form OknGlowne
     */
    public OknGlowne() {
        initComponents();
        jPanel_logowanie.setVisible(false);        
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_edytujSlownik.setVisible(false);
        jPanel_rejestracja.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_start = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel_logowanie = new javax.swing.JPanel();
        jTextField_login = new javax.swing.JTextField();
        jTextField_haslo = new javax.swing.JPasswordField();
        jLabel_login = new javax.swing.JLabel();
        jLabel_haslo = new javax.swing.JLabel();
        jButton_zaloguj = new javax.swing.JButton();
        jPanel_fiszkiWybor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel_fiszkiNauka = new javax.swing.JPanel();
        jTextField_fiszkiNauka_1slowko = new javax.swing.JTextField();
        jTextField_fiszkiNauka_2slowko = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel_ocena = new javax.swing.JPanel();
        jButton_ocena0 = new javax.swing.JButton();
        jButton_ocena1 = new javax.swing.JButton();
        jButton_ocena2 = new javax.swing.JButton();
        jButton_ocena3 = new javax.swing.JButton();
        jButton_ocena4 = new javax.swing.JButton();
        jButton_ocena5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton_fiszkiNauka_cofnij = new javax.swing.JButton();
        jButton_fiszkiNauka_Edytuj = new javax.swing.JButton();
        jButton_fiszkiNauka_Zapisz = new javax.swing.JButton();
        jPanel_edytujSlownik = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton_edytujSlownik = new javax.swing.JButton();
        jButton_dodajSlownik = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton_edytuj = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton_zapisz = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel_rejestracja = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_plik = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem_zakoncz = new javax.swing.JMenuItem();
        jMenu_narzedzia = new javax.swing.JMenu();
        jMenuItem_edytujSlownik = new javax.swing.JMenuItem();
        jMenu_pommoc = new javax.swing.JMenu();
        jMenuItem_oProgramie = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fiszki");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(480, 400));
        setPreferredSize(new java.awt.Dimension(460, 420));
        setResizable(false);

        jPanel_start.setPreferredSize(new java.awt.Dimension(460, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Witaj w programie Fiszki");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Zaloguj się by móc korzystać z programu");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Logowanie");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Rejestracja");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_startLayout = new javax.swing.GroupLayout(jPanel_start);
        jPanel_start.setLayout(jPanel_startLayout);
        jPanel_startLayout.setHorizontalGroup(
            jPanel_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_startLayout.createSequentialGroup()
                .addGroup(jPanel_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_startLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_startLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_startLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(73, 73, 73))
        );
        jPanel_startLayout.setVerticalGroup(
            jPanel_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_startLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(66, 66, 66))
        );

        jPanel_logowanie.setMaximumSize(new java.awt.Dimension(460, 400));
        jPanel_logowanie.setMinimumSize(new java.awt.Dimension(460, 400));
        jPanel_logowanie.setName(""); // NOI18N
        jPanel_logowanie.setPreferredSize(new java.awt.Dimension(460, 400));
        jPanel_logowanie.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel_logowanieComponentHidden(evt);
            }
        });

        jTextField_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_loginActionPerformed(evt);
            }
        });

        jTextField_haslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hasloActionPerformed(evt);
            }
        });

        jLabel_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_login.setText("Login");

        jLabel_haslo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_haslo.setText("Hasło");

        jButton_zaloguj.setText("Zaloguj");
        jButton_zaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_zalogujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_logowanieLayout = new javax.swing.GroupLayout(jPanel_logowanie);
        jPanel_logowanie.setLayout(jPanel_logowanieLayout);
        jPanel_logowanieLayout.setHorizontalGroup(
            jPanel_logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_logowanieLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel_logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_haslo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_logowanieLayout.createSequentialGroup()
                        .addComponent(jButton_zaloguj)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_logowanieLayout.createSequentialGroup()
                        .addGroup(jPanel_logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_haslo, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jTextField_login))
                        .addGap(187, 187, 187))))
        );
        jPanel_logowanieLayout.setVerticalGroup(
            jPanel_logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_logowanieLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel_logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel_logowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_haslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_haslo))
                .addGap(36, 36, 36)
                .addComponent(jButton_zaloguj)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jPanel_fiszkiWybor.setName(""); // NOI18N
        jPanel_fiszkiWybor.setPreferredSize(new java.awt.Dimension(460, 400));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Wybierz słownik z którego będziesz sie uczył");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Słownik1", "Słownik2", "Słownik3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_fiszkiWyborLayout = new javax.swing.GroupLayout(jPanel_fiszkiWybor);
        jPanel_fiszkiWybor.setLayout(jPanel_fiszkiWyborLayout);
        jPanel_fiszkiWyborLayout.setHorizontalGroup(
            jPanel_fiszkiWyborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fiszkiWyborLayout.createSequentialGroup()
                .addGroup(jPanel_fiszkiWyborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_fiszkiWyborLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton1))
                    .addGroup(jPanel_fiszkiWyborLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel_fiszkiWyborLayout.setVerticalGroup(
            jPanel_fiszkiWyborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fiszkiWyborLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel5)
                .addGap(70, 70, 70)
                .addGroup(jPanel_fiszkiWyborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        jPanel_fiszkiNauka.setPreferredSize(new java.awt.Dimension(460, 400));

        jTextField_fiszkiNauka_1slowko.setEditable(false);
        jTextField_fiszkiNauka_1slowko.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_fiszkiNauka_1slowko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fiszkiNauka_1slowkoActionPerformed(evt);
            }
        });

        jTextField_fiszkiNauka_2slowko.setEditable(false);
        jTextField_fiszkiNauka_2slowko.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jButton3.setText("Pokaż odpowiedź");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton_ocena0.setText("0");
        jButton_ocena0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ocena0ActionPerformed(evt);
            }
        });

        jButton_ocena1.setText("1");

        jButton_ocena2.setText("2");

        jButton_ocena3.setText("3");
        jButton_ocena3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ocena3ActionPerformed(evt);
            }
        });

        jButton_ocena4.setText("4");

        jButton_ocena5.setText("5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Oceń słówko");

        javax.swing.GroupLayout jPanel_ocenaLayout = new javax.swing.GroupLayout(jPanel_ocena);
        jPanel_ocena.setLayout(jPanel_ocenaLayout);
        jPanel_ocenaLayout.setHorizontalGroup(
            jPanel_ocenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ocenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_ocena0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ocena1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ocenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ocenaLayout.createSequentialGroup()
                        .addComponent(jButton_ocena2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ocena3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ocena4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ocena5))
                    .addGroup(jPanel_ocenaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_ocenaLayout.setVerticalGroup(
            jPanel_ocenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ocenaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel_ocenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ocena0)
                    .addComponent(jButton_ocena1)
                    .addComponent(jButton_ocena2)
                    .addComponent(jButton_ocena3)
                    .addComponent(jButton_ocena4)
                    .addComponent(jButton_ocena5))
                .addGap(56, 56, 56))
        );

        jButton_fiszkiNauka_cofnij.setText("Cofnij");
        jButton_fiszkiNauka_cofnij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fiszkiNauka_cofnijActionPerformed(evt);
            }
        });

        jButton_fiszkiNauka_Edytuj.setText("Edytuj");
        jButton_fiszkiNauka_Edytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fiszkiNauka_EdytujActionPerformed(evt);
            }
        });

        jButton_fiszkiNauka_Zapisz.setText("Zapisz");
        jButton_fiszkiNauka_Zapisz.setEnabled(false);
        jButton_fiszkiNauka_Zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fiszkiNauka_ZapiszActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_fiszkiNaukaLayout = new javax.swing.GroupLayout(jPanel_fiszkiNauka);
        jPanel_fiszkiNauka.setLayout(jPanel_fiszkiNaukaLayout);
        jPanel_fiszkiNaukaLayout.setHorizontalGroup(
            jPanel_fiszkiNaukaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_fiszkiNaukaLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jPanel_ocena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel_fiszkiNaukaLayout.createSequentialGroup()
                .addGroup(jPanel_fiszkiNaukaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_fiszkiNaukaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel_fiszkiNaukaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_fiszkiNauka_cofnij)
                            .addComponent(jTextField_fiszkiNauka_1slowko, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel_fiszkiNaukaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_fiszkiNauka_2slowko, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_fiszkiNauka_Edytuj)))
                    .addGroup(jPanel_fiszkiNaukaLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton_fiszkiNauka_Zapisz)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_fiszkiNaukaLayout.setVerticalGroup(
            jPanel_fiszkiNaukaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fiszkiNaukaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_fiszkiNaukaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_fiszkiNauka_cofnij)
                    .addComponent(jButton_fiszkiNauka_Edytuj))
                .addGap(39, 39, 39)
                .addGroup(jPanel_fiszkiNaukaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_fiszkiNauka_1slowko, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_fiszkiNauka_2slowko, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_fiszkiNauka_Zapisz)
                .addGap(3, 3, 3)
                .addComponent(jPanel_ocena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel_edytujSlownik.setPreferredSize(new java.awt.Dimension(460, 400));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Angielski", "Niemiecki", "Rosyjski" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jButton_edytujSlownik.setText("Edytuj słownik");
        jButton_edytujSlownik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edytujSlownikActionPerformed(evt);
            }
        });

        jButton_dodajSlownik.setText("Dodaj słownik");

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "dog", "cat", "yes", "no" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList3);

        jButton_edytuj.setText("Edytuj");
        jButton_edytuj.setEnabled(false);
        jButton_edytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edytujActionPerformed(evt);
            }
        });

        jTextField3.setText("pies");

        jButton_zapisz.setText("zapisz");
        jButton_zapisz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_zapisz.setEnabled(false);

        jTextField4.setText("dog");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton7.setText("Zakończ edycje");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_edytujSlownikLayout = new javax.swing.GroupLayout(jPanel_edytujSlownik);
        jPanel_edytujSlownik.setLayout(jPanel_edytujSlownikLayout);
        jPanel_edytujSlownikLayout.setHorizontalGroup(
            jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_edytujSlownikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addGroup(jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_edytujSlownikLayout.createSequentialGroup()
                        .addGroup(jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_edytujSlownikLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_edytujSlownik)
                                    .addComponent(jButton_dodajSlownik)))
                            .addGroup(jPanel_edytujSlownikLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7)
                                    .addGroup(jPanel_edytujSlownikLayout.createSequentialGroup()
                                        .addComponent(jButton_edytuj)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_edytujSlownikLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_zapisz)
                        .addGap(62, 62, 62))))
        );
        jPanel_edytujSlownikLayout.setVerticalGroup(
            jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_edytujSlownikLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_edytujSlownikLayout.createSequentialGroup()
                        .addComponent(jButton_dodajSlownik)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_edytujSlownik)))
                .addGap(47, 47, 47)
                .addGroup(jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_edytujSlownikLayout.createSequentialGroup()
                        .addGroup(jPanel_edytujSlownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_edytujSlownikLayout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_edytujSlownikLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton_edytuj)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_zapisz))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(50, 50, 50))
        );

        jLabel3.setText("Hasło");

        jLabel4.setText("Login");

        jLabel7.setText("Powtórz hasło");

        jLabel8.setText("Email");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField8.setToolTipText("");

        jButton5.setText("Zarejestruj");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_rejestracjaLayout = new javax.swing.GroupLayout(jPanel_rejestracja);
        jPanel_rejestracja.setLayout(jPanel_rejestracjaLayout);
        jPanel_rejestracjaLayout.setHorizontalGroup(
            jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_rejestracjaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jTextField8)
                    .addComponent(jPasswordField1)
                    .addComponent(jPasswordField2))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_rejestracjaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(117, 117, 117))
        );
        jPanel_rejestracjaLayout.setVerticalGroup(
            jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_rejestracjaLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jButton5)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(640, 640));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(640, 640));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(133, 20));

        jMenu_plik.setText("Plik");

        jMenuItem1.setText("Start");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_plik.add(jMenuItem1);

        jMenuItem2.setText("Wyloguj");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu_plik.add(jMenuItem2);

        jMenuItem_zakoncz.setText("Zakończ program");
        jMenuItem_zakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_zakonczActionPerformed(evt);
            }
        });
        jMenu_plik.add(jMenuItem_zakoncz);

        jMenuBar1.add(jMenu_plik);

        jMenu_narzedzia.setText("Narzędzia");

        jMenuItem_edytujSlownik.setText("Edytuj słownik");
        jMenuItem_edytujSlownik.setEnabled(false);
        jMenuItem_edytujSlownik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_edytujSlownikActionPerformed(evt);
            }
        });
        jMenu_narzedzia.add(jMenuItem_edytujSlownik);

        jMenuBar1.add(jMenu_narzedzia);

        jMenu_pommoc.setText("Pomoc");

        jMenuItem_oProgramie.setText("O programie");
        jMenuItem_oProgramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_oProgramieActionPerformed(evt);
            }
        });
        jMenu_pommoc.add(jMenuItem_oProgramie);

        jMenuBar1.add(jMenu_pommoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_logowanie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jPanel_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jPanel_fiszkiWybor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jPanel_fiszkiNauka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jPanel_edytujSlownik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_rejestracja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_logowanie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_fiszkiWybor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_fiszkiNauka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_edytujSlownik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_rejestracja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_zakonczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_zakonczActionPerformed
System.exit(0);
    }//GEN-LAST:event_jMenuItem_zakonczActionPerformed

    private void jMenuItem_edytujSlownikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_edytujSlownikActionPerformed
        jPanel_edytujSlownik.setVisible(true);
        jPanel_logowanie.setVisible(false);        
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_start.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_edytujSlownikActionPerformed

    private void jPanel_logowanieComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_logowanieComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_logowanieComponentHidden

    private void jTextField_hasloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hasloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hasloActionPerformed

    private void jTextField_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_loginActionPerformed

    private void jMenuItem_oProgramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_oProgramieActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Fiszki Program \n V 0.5.3 \n By Kamil Jaroniec, Łukasz Wójciuk, Andrzej Kopiec", "O programie", 1);
    }//GEN-LAST:event_jMenuItem_oProgramieActionPerformed

    private void jButton_zalogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_zalogujActionPerformed
      String login=jTextField_login.getText();
        String haslo=jTextField_haslo.getText();
        String [] llogin=new String[10];
        String [] hhaslo=new String[10];
       try{
            String host= "jdbc:derby://localhost:1527/Baza";
            String uName = "admin93";
            String uPass= "admin";
            Connection con = DriverManager.getConnection( host, uName, uPass );
            Statement stmt = con.createStatement( );
            String SQL = "select * from ADMIN93.LOGOWANIE";
            ResultSet rs = stmt.executeQuery( SQL );
            
           for(int i=0;i<10;i++){
            rs.next( );
            int id_col = rs.getInt("ID");
            llogin[i]= rs.getString("LOGIN");
            hhaslo[i] = rs.getString("HASLO");}
           
            
            
        }
        catch (SQLException err) {
            System.out.println(err.getMessage());
        }
       for(int i=0;i<10;i++)
       if(login.equals(llogin[i])){
           if(haslo.equals(hhaslo[i])){
           
        jPanel_fiszkiWybor.setVisible(true);
        jPanel_logowanie.setVisible(false);        
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_start.setVisible(false);
        jMenuItem_edytujSlownik.setEnabled(true);}
       }
    }//GEN-LAST:event_jButton_zalogujActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel_fiszkiNauka.setVisible(true);
        jPanel_logowanie.setVisible(false);        
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_start.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanel_ocena.setVisible(true);
        jPanel_logowanie.setVisible(false);        
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_start.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_ocena0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ocena0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ocena0ActionPerformed

    private void jButton_ocena3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ocena3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ocena3ActionPerformed

    private void jButton_edytujSlownikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edytujSlownikActionPerformed
        jButton_edytuj.setEnabled(true);
        jButton_zapisz.setEnabled(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton_edytujSlownikActionPerformed

    private void jButton_edytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edytujActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_edytujActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel_logowanie.setVisible(true);
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_start.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Zarejestrowano!");
        jPanel_rejestracja.setVisible(false);
        jPanel_logowanie.setVisible(false);
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_start.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel_rejestracja.setVisible(true);
        jPanel_logowanie.setVisible(false);
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_start.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField_fiszkiNauka_1slowkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fiszkiNauka_1slowkoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fiszkiNauka_1slowkoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanel_edytujSlownik.setVisible(false);
        jPanel_rejestracja.setVisible(false);
        jPanel_logowanie.setVisible(false);
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_start.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton_fiszkiNauka_cofnijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fiszkiNauka_cofnijActionPerformed
        jPanel_rejestracja.setVisible(false);
        jPanel_logowanie.setVisible(false);
        jPanel_fiszkiWybor.setVisible(true);
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_start.setVisible(false);
    }//GEN-LAST:event_jButton_fiszkiNauka_cofnijActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jPanel_rejestracja.setVisible(false);
        jPanel_logowanie.setVisible(false);
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_start.setVisible(true);
        jMenuItem_edytujSlownik.setEnabled(false);
        jTextField_login.setText(null);
        jTextField_haslo.setText(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jPanel_edytujSlownik.setVisible(false);
        jPanel_rejestracja.setVisible(false);
        jPanel_logowanie.setVisible(false);
        jPanel_fiszkiWybor.setVisible(false);
        jPanel_fiszkiNauka.setVisible(false);
        jPanel_ocena.setVisible(false);
        jPanel_start.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton_fiszkiNauka_EdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fiszkiNauka_EdytujActionPerformed
       jTextField_fiszkiNauka_1slowko.setEditable(true);
       jTextField_fiszkiNauka_2slowko.setEditable(true);
       jButton_fiszkiNauka_Zapisz.setEnabled(true);
    }//GEN-LAST:event_jButton_fiszkiNauka_EdytujActionPerformed

    private void jButton_fiszkiNauka_ZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fiszkiNauka_ZapiszActionPerformed
       jTextField_fiszkiNauka_1slowko.setEditable(false);
       jTextField_fiszkiNauka_2slowko.setEditable(false);
       jButton_fiszkiNauka_Zapisz.setEnabled(false);
    }//GEN-LAST:event_jButton_fiszkiNauka_ZapiszActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try{
            String host= "jdbc:derby://localhost:1527/Baza";
            String uName = "admin93";
            String uPass= "admin";
        
        Connection con=DriverManager.getConnection(host, uName, uPass);
        }
        catch (SQLException err) {
            System.out.println(err.getMessage());
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknGlowne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknGlowne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_dodajSlownik;
    private javax.swing.JButton jButton_edytuj;
    private javax.swing.JButton jButton_edytujSlownik;
    private javax.swing.JButton jButton_fiszkiNauka_Edytuj;
    private javax.swing.JButton jButton_fiszkiNauka_Zapisz;
    private javax.swing.JButton jButton_fiszkiNauka_cofnij;
    private javax.swing.JButton jButton_ocena0;
    private javax.swing.JButton jButton_ocena1;
    private javax.swing.JButton jButton_ocena2;
    private javax.swing.JButton jButton_ocena3;
    private javax.swing.JButton jButton_ocena4;
    private javax.swing.JButton jButton_ocena5;
    private javax.swing.JButton jButton_zaloguj;
    private javax.swing.JButton jButton_zapisz;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_haslo;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JList jList1;
    private javax.swing.JList jList3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_edytujSlownik;
    private javax.swing.JMenuItem jMenuItem_oProgramie;
    private javax.swing.JMenuItem jMenuItem_zakoncz;
    private javax.swing.JMenu jMenu_narzedzia;
    private javax.swing.JMenu jMenu_plik;
    private javax.swing.JMenu jMenu_pommoc;
    private javax.swing.JPanel jPanel_edytujSlownik;
    private javax.swing.JPanel jPanel_fiszkiNauka;
    private javax.swing.JPanel jPanel_fiszkiWybor;
    private javax.swing.JPanel jPanel_logowanie;
    private javax.swing.JPanel jPanel_ocena;
    private javax.swing.JPanel jPanel_rejestracja;
    private javax.swing.JPanel jPanel_start;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField_fiszkiNauka_1slowko;
    private javax.swing.JTextField jTextField_fiszkiNauka_2slowko;
    private javax.swing.JPasswordField jTextField_haslo;
    private javax.swing.JTextField jTextField_login;
    // End of variables declaration//GEN-END:variables
}
